[package]
name = "pinpoint"
version = "0.1.0"
authors = ["Yutaka Kamei <kamei@yykamei.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.19.0", default-features = false }

[dev-dependencies]
tempfile = "3.2.0"
