[package]
name = "thwack"
description = "Command line version of Go To File utility, similar to the one on GitHub"
authors = ["Yutaka Kamei <kamei@yykamei.me>"]
homepage = "https://github.com/yykamei/thwack"
repository = "https://github.com/yykamei/thwack"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
edition = "2018"
version = "0.6.0"

[dependencies]
crossterm = "0.23.0"
git2 = { version = "0.14.0", default-features = false }
libc = "0.2.119"
log = { version = "0.4.14", features = ["std"] }
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[dev-dependencies]
tempfile = "3.3.0"
