[package]
name = "thwack"
description = "Command line version of Go To File utility, similar to the one on GitHub"
authors = ["Yutaka Kamei <kamei@yykamei.me>"]
homepage = "https://github.com/yykamei/thwack"
repository = "https://github.com/yykamei/thwack"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
edition = "2021"
rust-version = "1.59.0"
version = "0.7.2"

[dependencies]
copypasta = "0.8.0"
crossterm = "0.23.2"
git2 = { version = "0.14.4", default-features = false }
libc = "0.2.126"
log = { version = "0.4.17", features = ["std"] }
unicode-segmentation = "1.9.0"
unicode-width = "0.1.9"

[dev-dependencies]
tempfile = "3.3.0"
