[package]
name = "thwack"
description = "Command line version of Go To File utility, similar to the one on GitHub"
authors = ["Yutaka Kamei <kamei@yykamei.me>"]
homepage = "https://github.com/yykamei/thwack"
repository = "https://github.com/yykamei/thwack"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
edition = "2021"
rust-version = "1.59.0"
version = "0.8.13"

[dependencies]
copypasta = "0.8.2"
crossterm = "0.26.1"
git2 = { version = "0.17.2", default-features = false }
libc = "0.2.146"
log = { version = "0.4.18", features = ["std"] }
unicode-segmentation = "1.10.1"
unicode-width = "0.1.10"

[dev-dependencies]
tempfile = "3.6.0"
